{
    "name": "GoldVerse Premium Laundry Branding",
    "summary": "Client-specific login branding for the GoldVerse Premium Laundry tenant",
    "version": "19.0.1.0.0",
    "category": "Services/Laundry",
    "author": "AimAze Tech Solutions",
    "website": "https://aimazetechsolutions.com",
    "license": "LGPL-3",
    "depends": [
        "aimaze_laundry_management",
        "base_accounting_kit",
        "l10n_pk",
        "mail",
        "web",
    ],
    "data": [
        "security/customer_care_security.xml",
        "security/ir.model.access.csv",
        "data/admin_access.xml",
        "data/pakistan_defaults.xml",
        "data/customer_type_defaults.xml",
        "data/cash_management_data.xml",
        "data/customer_wallet_receipt_data.xml",
        "data/payment_method_defaults.xml",
        "data/goldverse_dropdown_data.xml",
        "data/goldverse_colour_code_defaults.xml",
        "data/goldverse_qc_addon_data.xml",
        "data/service_line_detail_sync.xml",
        "data/order_flow_defaults.xml",
        "data/menu_cleanup.xml",
        "data/customer_care_menus.xml",
        "views/login_branding_views.xml",
        "views/partner_views.xml",
        "views/role_access_manager_views.xml",
        "views/goldverse_config_views.xml",
        "views/cash_management_views.xml",
        "views/customer_wallet_receipt_views.xml",
        "views/laundry_payment_wizard_views.xml",
        "views/account_move_line_views.xml",
        "views/account_product_views.xml",
        "views/laundry_receipt_views.xml",
        "views/complaint_views.xml",
        "views/report_export_templates.xml",
        "views/dashboard_views.xml",
        "data/dashboard_defaults.xml",
        "views/order_line_views.xml",
        "views/order_flow_views.xml",
        "views/pickup_delivery_views.xml",
        "views/sales_register_views.xml",
        "views/laundry_dashboard_filters.xml",
        "views/laundry_dashboard_export.xml",
        "views/dashboard_drill_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            (
                "before",
                "web/static/src/webclient/menus/menu_service.js",
                "goldverse_premium_laundry_branding/static/src/js/goldverse_menu_storage_guard.js",
            ),
            "goldverse_premium_laundry_branding/static/src/js/goldverse_account_report_drilldown.js",
            "goldverse_premium_laundry_branding/static/src/js/goldverse_dashboard_cards.js",
            "goldverse_premium_laundry_branding/static/src/js/goldverse_laundry_list_columns.js",
            "goldverse_premium_laundry_branding/static/src/js/goldverse_partner_lock.js",
            "goldverse_premium_laundry_branding/static/src/js/goldverse_dashboard_role.js",
            "goldverse_premium_laundry_branding/static/src/js/goldverse_report_date_filters.js",
            "goldverse_premium_laundry_branding/static/src/js/goldverse_pwa_install_prompt.js",
            "goldverse_premium_laundry_branding/static/src/xml/goldverse_account_report_drilldown.xml",
            "goldverse_premium_laundry_branding/static/src/xml/goldverse_report_date_filters.xml",
            "goldverse_premium_laundry_branding/static/src/scss/goldverse_backend.scss",
            "goldverse_premium_laundry_branding/static/src/scss/goldverse_dashboard.scss",
        ],
    },
    "application": False,
    "installable": True,
}
