{
    "name": "AimAze Laundry ERP",
    "summary": "Professional laundry ERP for UAE and Pakistan businesses powered by Odoo",
    "version": "19.0.3.0.29",
    "category": "Services/Laundry",
    "author": "AimAze Tech Solutions",
    "website": "https://aimazetechsolutions.com",
    "license": "LGPL-3",
    "depends": [
        "account",
        "base_accounting_kit",
        "contacts",
        "hr",
        "mail",
        "maintenance",
        "payment",
        "point_of_sale",
        "portal",
        "product",
        "purchase",
        "sale_management",
        "stock",
        "web",
    ],
    "data": [
        "security/laundry_security.xml",
        "security/ir.model.access.csv",
        "data/laundry_sequences.xml",
        "data/laundry_master_data.xml",
        "data/laundry_phase2_data.xml",
        "data/laundry_phase3_data.xml",
        "data/laundry_phase4_data.xml",
        "data/laundry_country_defaults.xml",
        "data/laundry_demo_data.xml",
        "views/laundry_dashboard_views.xml",
        "views/laundry_order_views.xml",
        "views/laundry_configuration_views.xml",
        "views/laundry_operations_views.xml",
        "views/laundry_accounting_views.xml",
        "wizard/laundry_payment_wizard_views.xml",
        "wizard/laundry_quick_order_wizard_views.xml",
        "wizard/laundry_phase3_wizard_views.xml",
        "views/laundry_phase2_views.xml",
        "views/laundry_phase3_views.xml",
        "views/laundry_phase4_views.xml",
        "views/laundry_phase5_views.xml",
        "views/laundry_portal_templates.xml",
        "report/laundry_reports.xml",
        "report/laundry_report_templates.xml",
        "views/laundry_menus.xml",
        "data/laundry_menu_cleanup.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "aimaze_laundry_management/static/src/scss/aimaze_theme.scss",
            "aimaze_laundry_management/static/src/scss/laundry_backend.scss",
            "aimaze_laundry_management/static/src/scss/account_report_patch.scss",
            "aimaze_laundry_management/static/src/scss/accounting_dashboard.scss",
            "aimaze_laundry_management/static/src/js/aimaze_kpi_widget.js",
            "aimaze_laundry_management/static/src/js/account_report_date_filter.js",
            "aimaze_laundry_management/static/src/js/account_report_drilldown.js",
            "aimaze_laundry_management/static/src/js/dashboard_range_filter.js",
            "aimaze_laundry_management/static/src/xml/account_report_date_filter.xml",
            "aimaze_laundry_management/static/src/xml/aimaze_kpi_widget.xml",
        ],
        "web.assets_web": [
            "aimaze_laundry_management/static/src/scss/aimaze_theme.scss",
            "aimaze_laundry_management/static/src/scss/laundry_backend.scss",
            "aimaze_laundry_management/static/src/scss/account_report_patch.scss",
            "aimaze_laundry_management/static/src/scss/accounting_dashboard.scss",
            "aimaze_laundry_management/static/src/js/aimaze_kpi_widget.js",
            "aimaze_laundry_management/static/src/js/account_report_date_filter.js",
            "aimaze_laundry_management/static/src/js/account_report_drilldown.js",
            "aimaze_laundry_management/static/src/js/dashboard_range_filter.js",
            "aimaze_laundry_management/static/src/xml/account_report_date_filter.xml",
            "aimaze_laundry_management/static/src/xml/aimaze_kpi_widget.xml",
        ],
        "web.assets_frontend": [
            "aimaze_laundry_management/static/src/scss/aimaze_theme.scss",
        ],
    },
    "demo": [
        "demo/laundry_phase3_demo.xml",
        "demo/laundry_phase4_demo.xml",
    ],
    "application": True,
    "installable": True,
}
