from . import pakistan_defaults
from . import goldverse_config
from . import res_partner
from . import laundry_order
from . import laundry_order_line
from . import laundry_payment_wizard
from . import interactive_account_report
from . import dashboard
from . import account_journal
from . import role_access_manager
